name: CI for WPametu

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        php: [ '7.4', '8.0' ] # PHP versions to check.
        wp: [ 'latest', '6.1' ]      # WordPress version to check.
    uses: tarosky/workflows/.github/workflows/wp-unit-test.yml@main
    name: PHP Unit Test with PHP ${{ matrix.php }} and WP ${{ matrix.wp }}
    with:
      php_version: ${{ matrix.php }}
      wp_version: ${{ matrix.wp }}

  lint:
    runs-on: ubuntu-latest
    name: PHP Syntax Check
    steps:
      - uses: actions/checkout@master

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHP Lint
        run: composer lint

  assets:
    runs-on: ubuntu-latest
    name: Assets Test
    steps:
      - uses: actions/checkout@master

      - name: Install NPM
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Packages
        run: npm install

      - name: Stylelint and ESlint
        run: npm run lint

      - name: Check Build succeed
        run: npm run build

  status-check:
    runs-on: ubuntu-latest
    name: Check Status
    needs: [test, assets, lint]
    if: always()
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
